function ghostsgame(){var bb='',$=' top: -1000px;',yb='" for "gwt:onLoadErrorFn"',wb='" for "gwt:onPropertyErrorFn"',hb='");',zb='#',Bc='.cache.js',Bb='/',Hb='//',gc='0556A491C6ECEA41307DC4DA7BD92962',hc='077344116CC79B2072598EC1E9C28960',ic='141A7823FFE661B7CC0F2A9AC9F7A5EC',jc='22A20D472247F2751E4ED30808846020',kc='24176F1AABAD3B3C33B222A56511D4D2',lc='279C23C9A0B5B79243326510CCB99BCF',mc='3DEB11F02D0F57F413ECD504E64242D1',nc='621F2C3E21893566F344FDCB55353D98',oc='6462F0EB49A2C2EA48DAFC9714F49198',pc='75156C19D534E24D90BDEFB2E3BBD04B',qc='8BC27861BF6092CC65FE896A409FA4FB',rc='901B1E133D5A748E88D8650667990237',Ac=':',qb='::',Nc=':moduleBase',ab='<!doctype html>',cb='<html><head><\/head><body><\/body><\/html>',tb='=',Ab='?',sc='A459F0467FDFC78BC98719601D69ED20',tc='BB2ECE97B812A46DE541C2F104B12FD9',uc='BE8DE4FD93760C61539FCFFFF49568E8',vb='Bad handler "',vc='C3D9E7CB512D317B9FA06F22780C4647',_='CSS1Compat',fb='Chrome',wc='DCAA8E50A0C123D038EEA8924AA63DC6',eb='DOMContentLoaded',V='DUMMY',xc='E044DC07155BF5B60E5F573033D4D209',yc='F1AB618D0387FCAECFE13A1FF3CEAA27',zc='FCD298F81C8D8469E5F421CB930C3D50',Mc='Ignoring non-whitelisted Dev Mode URL: ',Lc='__gwtDevModeHook:ghostsgame',Jb='android',Lb='android_tablet',Gb='base',Eb='baseUrl',Q='begin',Rb='blackberry',W='body',P='bootstrap',Db='clear.cache.gif',sb='content',Sb='desktop',Ic='end',gb='eval("',Kc='file:',bc='gecko',cc='gecko1_8',T='ghostsgame',fc='ghostsgame.devmode.js',Fb='ghostsgame.nocache.js',pb='ghostsgame::',R='gwt.codesvr.ghostsgame=',S='gwt.codesvr=',Hc='gwt/clean/clean.css',xb='gwt:onLoadErrorFn',ub='gwt:onPropertyErrorFn',rb='gwt:property',mb='head',Fc='href',Jc='http:',$b='ie10',ac='ie8',_b='ie9',X='iframe',Cb='img',Mb='ipad',Nb='ipad_retina',Ob='iphone',Pb='ipod',jb='javascript',Y='javascript:""',Cc='link',Gc='loadExternalRefs',nb='meta',Ib='mgwt.os',Kb='mobile',Tb='mobile.user.agent',Ub='mobilesafari',lb='moduleRequested',kb='moduleStartup',Zb='msie',ob='name',Vb='not_mobile',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',Dc='rel',Qb='retina',Yb='safari',ib='script',ec='selectingPermutation',U='startup',Ec='stylesheet',db='undefined',dc='unknown',Wb='user.agent',Xb='webkit';var o=window;var p=document;r(P,Q);function q(){var a=o.location.search;return a.indexOf(R)!=-1||a.indexOf(S)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:T,sessionId:o.__gwtStatsSessionId,subSystem:U,evtGroup:a,millis:(new Date).getTime(),type:b})}}
ghostsgame.__sendStats=r;ghostsgame.__moduleName=T;ghostsgame.__errFn=null;ghostsgame.__moduleBase=V;ghostsgame.__softPermutationId=0;ghostsgame.__computePropValue=null;ghostsgame.__getPropMap=null;ghostsgame.__gwtInstallCode=function(){};ghostsgame.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[T]={moduleName:T};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(W)[0]}
function B(){if(v){return}var a=p.createElement(X);a.src=Y;a.id=T;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==_?ab:bb;v.write(b+cb);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(gb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(hb));g=f.createElement(ib);g.language=jb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(ib);g.language=jb;g.text=c[i];e.appendChild(g);d(e,g)}}}
ghostsgame.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;p.getElementsByTagName(mb)[0].appendChild(n)}
ghostsgame.__startLoadingFragment=function(a){return G(a)};ghostsgame.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(ib);c.language=jb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(nb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(ob),k;if(j){j=j.replace(pb,bb);if(j.indexOf(qb)>=0){continue}if(j==rb){k=i.getAttribute(sb);if(k){var l,m=k.indexOf(tb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=bb}c[j]=l}}else if(j==ub){k=i.getAttribute(sb);if(k){try{d=eval(k)}catch(a){alert(vb+k+wb)}}}else if(j==xb){k=i.getAttribute(sb);if(k){try{e=eval(k)}catch(a){alert(vb+k+yb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;ghostsgame.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(zb);if(b==-1){b=a.length}var c=a.indexOf(Ab);if(c==-1){c=a.length}var d=a.lastIndexOf(Bb,Math.min(c,b));return d>=0?a.substring(0,d+1):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Cb);b.src=a+Db;a=e(b.src)}return a}
function g(){var a=t(Eb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Fb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Gb);if(a.length>0){return a[a.length-1].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Hb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return ghostsgame.__moduleBase+a}
function H(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Ib]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Jb)!=-1){if(a.indexOf(Kb)!=-1){return Jb}else{return Lb}}if(a.indexOf(Mb)!=-1){if(window.devicePixelRatio>=2){return Nb}return Mb}if(a.indexOf(Ob)!=-1||a.indexOf(Pb)!=-1){if(window.devicePixelRatio>=2){return Qb}return Ob}if(a.indexOf(Rb)!=-1){return Rb}return Sb}();return b}};i[Ib]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};j[Tb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Ub:Vb};i[Tb]={mobilesafari:0,not_mobile:1};j[Wb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Xb)!=-1}())return Yb;if(function(){return b.indexOf(Zb)!=-1&&p.documentMode>=10}())return $b;if(function(){return b.indexOf(Zb)!=-1&&p.documentMode>=9}())return _b;if(function(){return b.indexOf(Zb)!=-1&&p.documentMode>=8}())return ac;if(function(){return b.indexOf(bc)!=-1}())return cc;return dc};i[Wb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};s=function(a,b){return b in i[a]};ghostsgame.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};ghostsgame.__computePropValue=k;o.__gwt_activeModules[T].bindings=ghostsgame.__getPropMap;r(P,ec);if(q()){return G(fc)}var l;try{h([Rb,Ub,Yb],gc);h([Mb,Ub,Yb],hc);h([Lb,Ub,Yb],ic);h([Ob,Vb,Yb],jc);h([Sb,Vb,_b],kc);h([Jb,Vb,Yb],lc);h([Lb,Vb,Yb],mc);h([Sb,Vb,Yb],nc);h([Sb,Ub,Yb],oc);h([Rb,Vb,Yb],pc);h([Sb,Vb,cc],qc);h([Nb,Ub,Yb],rc);h([Nb,Vb,Yb],sc);h([Ob,Ub,Yb],tc);h([Qb,Vb,Yb],uc);h([Mb,Vb,Yb],vc);h([Sb,Vb,$b],wc);h([Sb,Vb,ac],xc);h([Qb,Ub,Yb],yc);h([Jb,Ub,Yb],zc);l=f[k(Ib)][k(Tb)][k(Wb)];var m=l.indexOf(Ac);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}ghostsgame.__softPermutationId=g;return G(l+Bc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(Cc);b.setAttribute(Dc,Ec);b.setAttribute(Fc,G(a));p.getElementsByTagName(mb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(Gc,Q);c(Hc);r(Gc,Ic)}
D();ghostsgame.__moduleBase=F();u[T].moduleBase=ghostsgame.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==Jc||o.location.protocol==Kc);o.__gwt_activeModules[T].canRedirect=K;if(K){var L=Lc;var M=o.sessionStorage[L];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(M)){if(M&&(window.console&&console.log)){console.log(Mc+M)}M=bb}if(M&&!o[L]){o[L]=true;o[L+Nc]=F();var N=p.createElement(ib);N.src=M;var O=p.getElementsByTagName(mb)[0];O.insertBefore(N,O.firstElementChild||O.children[0]);return false}}}I();r(P,Ic);C(J);return true}
ghostsgame.succeeded=ghostsgame();